### ISSUE TITLE
Criar uma branch dev no repositório

### ISSUE THREAD

**Issue by ProfAndrea** [JeanCarlosMartin/TrabalhoWEB#1]
Vão proteger a branch main para push

**Comment by JeanCarlosMartin** [comment]
Para mudar a dev para default, fui até as settings e na opção Branches, fiz as mudanças necessárias;
 E para bloquear a branch main, fui fui até as settings e na opção Branch, acessei a opção edit para criar a regra que realiza o bloqueio, sendo essa  a opção "Require a pull request before merging".
